#!/usr/bin/env python3
"""Generate requirements.txt from downloaded wheel/tarball files in packages/."""
import re
import sys
from pathlib import Path


def main() -> None:
    packages_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("packages")
    if not packages_dir.is_dir():
        print(f"[错误] {packages_dir} 目录不存在，请先运行 setup_offline download", file=sys.stderr)
        sys.exit(1)

    # Wheel: {distribution}-{version}(-{build})?-{py}-{abi}-{plat}.whl
    # Sdist:  {distribution}-{version}.tar.gz
    pattern = re.compile(r"^([a-zA-Z0-9_.-]+?)-(\d[^-]*)")

    # 已知的归档/包后缀，需从版本号中剥离
    _ARCHIVE_SUFFIXES = (".tar.gz", ".tar.bz2", ".tar.xz", ".tar", ".zip", ".tgz")

    def _clean_version(raw: str) -> str:
        """从原始匹配结果中剥离归档后缀，确保版本号为纯 semver。"""
        for suffix in _ARCHIVE_SUFFIXES:
            if raw.endswith(suffix):
                return raw[:-len(suffix)]
        return raw

    pkgs: dict[str, str] = {}
    for ext in ("*.whl", "*.tar.gz"):
        for f in sorted(packages_dir.glob(ext)):
            m = pattern.match(f.name)
            if m:
                name = m.group(1).replace("_", "-").lower()
                version = _clean_version(m.group(2))
                pkgs[name] = version

    output = packages_dir / "requirements.txt"
    with open(output, "w", encoding="utf-8") as out:
        out.write("# SmartSuite offline requirements\n")
        out.write("# Generated by setup_offline download\n")
        out.write("# Install: pip install --no-index --find-links=. -r requirements.txt\n")
        out.write("\n")
        for name in sorted(pkgs):
            out.write(f"{name}=={pkgs[name]}\n")

    print(f"  已生成 packages/requirements.txt ({len(pkgs)} 个包)")


if __name__ == "__main__":
    main()
