#!/usr/bin/env python3
"""Generate requirements.txt from downloaded wheel/tarball files in packages/."""

import re
import sys
from pathlib import Path

# Wheel 文件名: {dist}-{version}(-{build})?-{py}-{abi}-{plat}.whl
# 发行名与版本中的 '-'/'_' 在 wheel 名里已规范化为 '_'，故 '-' 仅作字段分隔符。
_WHEEL_RE = re.compile(r"^([a-zA-Z0-9_.-]+?)-(\d[^-]*)")

# sdist 支持的归档后缀（长后缀在前，避免 ".tar" 吞掉 ".tar.gz"）
_SDIST_EXTS = (".tar.gz", ".tar.bz2", ".tar.xz", ".tgz", ".tar", ".zip")


def _parse_wheel(filename: str):
    """解析 wheel 文件名 -> (name, version)。"""
    m = _WHEEL_RE.match(filename)
    if not m:
        return None
    name = m.group(1).replace("_", "-").lower()
    return name, m.group(2)


def _parse_sdist(filename: str):
    """解析 sdist 文件名 -> (name, version)。

    sdist 版本可含连字符预发布号（如 1.0-rc1），故不能沿用 wheel 的分隔符规则：
    取第一个 '-数字' 作为版本起点（PEP 440 版本以数字开头，后续可含 '-'）。
    """
    body = filename
    for suffix in _SDIST_EXTS:
        if body.endswith(suffix):
            body = body[: -len(suffix)]
            break
    m = re.search(r"-(\d)", body)
    if not m:
        return None
    name = body[: m.start()].replace("_", "-").lower()
    return name, body[m.start() + 1 :]


def main() -> None:
    packages_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("packages")
    if not packages_dir.is_dir():
        print(f"[错误] {packages_dir} 目录不存在，请先运行 setup_offline download", file=sys.stderr)
        sys.exit(1)

    pkgs: dict[str, str] = {}
    for ext in ("*.whl", "*.tar.gz", "*.tar.bz2", "*.tar.xz", "*.tgz", "*.zip"):
        for f in sorted(packages_dir.glob(ext)):
            parsed = _parse_wheel(f.name) if f.name.endswith(".whl") else _parse_sdist(f.name)
            if parsed:
                pkgs[parsed[0]] = parsed[1]

    output = packages_dir / "requirements.txt"
    with open(output, "w", encoding="utf-8") as out:
        out.write("# SmartSuite offline requirements\n")
        out.write("# Generated by setup_offline download\n")
        out.write("# Install: pip install --no-index --find-links=. -r requirements.txt\n")
        out.write("\n")
        for name in sorted(pkgs):
            out.write(f"{name}=={pkgs[name]}\n")

    print(f"  已生成 packages/requirements.txt ({len(pkgs)} 个包)")


if __name__ == "__main__":
    main()
